task_8 done
Caveman21days/js_tnk pull request #10
Opened 2022-07-31 11:27 UTC by Caveman21days

2022-07-31 13:37 UTC, PonomareVlad commented on task_8/custom_promises.js
> +  }
[Так сделайте](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Classes/Private_class_fields) 🙂

2022-07-31 14:08 UTC, PonomareVlad commented on task_8/custom_promises.js
> +  }
[Подробное объяснение](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_With_Private_Class_Features)

2022-07-31 17:08 UTC, Caveman21days commented on task_8/custom_promises.js
> +  }
Не принято до доработок?

2022-07-31 18:43 UTC, PonomareVlad commented on task_8/custom_promises.js
> +  }
Пока есть вопросы только к отлову ошибок, если хотите доработать, то проведу ревью после 🙂

2022-08-01 07:10 UTC, Caveman21days commented on task_8/custom_promises.js
> +  }
Добавил, ждемс)

2022-08-02 08:17 UTC, PonomareVlad requested changes

2022-08-02 08:17 UTC, PonomareVlad commented on task_8/custom_promises.js
> +}
Нужно проверить соответствие спецификации [`Promise.resolve()`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve)
```js
const request = fetch('https://api.ipify.org?format=json')
Promise.resolve(request).then(response => response.json()).then(console.debug) // {ip: "..."}

const request2 = fetch('https://api.ipify.org?format=json')
CustomPromiseByClass.resolve(request2).then(response => response.json()).then(console.debug)
// TypeError: null is not an object (evaluating 'response.json')
```

2022-08-04 14:19 UTC, PonomareVlad commented on task_8/custom_promises.js
> +}
Попробуйте проверить еще раз этот пример, т.к. у меня в последнем коммите выпадает ошибка: 
`"|this| is not a Promise"`

А в аргументе resolver-функции блока `.then(resolverFn)` передается экземпляр класса `CustomPromiseByClass`, вместо результата выполнения промиса, полученного в блоке `.resolve(promise)`

2022-08-04 14:22 UTC, PonomareVlad commented on task_8/custom_promises.js
> +}
Также обратите внимание на эту строку из [спецификации](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve):

> Если переданное значение является thenable - объект (т.е. имеет метод ["then" method](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)), возвращаемый промис будет следовать thenable - объекту, принимая своё состояние; в ином случае возвращаемый промис будет выполнен с переданным значением.

2022-08-04 16:18 UTC, Caveman21days commented on task_8/custom_promises.js
> +}
@PonomareVlad у меня нет такой ошибки. Плюс ваш код из примера у меня тоже не работает
`const url = 'https://api.ipify.org?format=json'

Promise.resolve(fetch(url)).then(response => response.json()).then(console.debug) // {ip: ...}

Promise {<pending>}

VM146:3          GET https://api.ipify.org/?format=json net::ERR_FAILED
(anonymous) @ VM146:3
VM146:3          Uncaught (in promise) TypeError: Failed to fetch
    at <anonymous>:3:17`

2022-08-05 07:41 UTC, PonomareVlad commented on task_8/custom_promises.js
> +}
[Собрал демку из последнего коммита](https://codepen.io/PonomareVlad/pen/YzaLXod)

2022-08-05 07:50 UTC, PonomareVlad commented on task_8/custom_promises.js
> +}
> в целом, мне кажется, это выходит за рамки курса)

На мой взгляд, такая конструкция не сильно выходит за рамки курса:

```js
static resolve = function(arg) {

     /* ... */

     if (typeof arg.then === 'function') {
       return arg
     }

     /* ... */

 }
```

2022-08-05 07:52 UTC, PonomareVlad commented on task_8/custom_promises.js
> +}
В любом случае, предлагаю остановиться на этом, т.к. базовые возможности уже уже давно реализованы 🙂

2022-08-05 07:53 UTC, PonomareVlad approved these changes

2022-08-05 08:16 UTC, merged