task_2 done
Caveman21days/js_tnk pull request #2
Opened 2022-06-22 18:36 UTC by Caveman21days

2022-06-24 10:43 UTC, PonomareVlad requested changes
Нужно исправить выполнение третьей задачи

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/1.js
> +console.log(toArr('Hello mr reviewer'))
Попробуйте вызвать функцию со строкой: 
```suggestion
console.log(toArr(`Hey,
mr  student !`))
```

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/1.js
> +console.log(toArr('Hello mr reviewer'))
В рамках курса задание выполнено корректно, но если вас будут беспокоить недостатки реализации, то можете попробовать исправить их без регулярных выражений, с помощью методов [trim()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/Trim) и [replaceAll()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll) 😉

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/2.js
> +}
```js
pairComp(["я", "это", "не", "буду"], ["я", "буду", "не", "это"])
```

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/2.js
> +}
```js
pairComp2([1,,,4], [1,2,3,4])
```

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/6.js
> +}
Чтобы определить, какая функция реализует задание наиболее правильным образом, попробуйте сравнить вызов этих функций на массиве с парными значениями, например `[0, 0, 1, 1]`
```js
const testCases = Array(10).fill()

console.group('randSort')
console.dir(testCases.map(() => randSort([0, 0, 1, 1])))
console.groupEnd()

console.group('shuffle')
console.dir(testCases.map(() => shuffle([0, 0, 1, 1])))
console.groupEnd()
```

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/7.js
> +})
Полагаю, что можно сократить объявление нового объекта, если нет необходимости в назначении специальных атрибутов для его свойств
```suggestion
const obj = {
  name: 'Alex',
  lastName: 'Smith'
}
```

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/8.js
> +  }
Было бы удобнее, если при установке даты рождения можно было бы использовать такой же тип данных (String) как и при ее чтении, например:

```js
user_one.dateOfBirth = user_two.dateOfBirth // TypeError
```

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/8.js
> +  },
Как можно учесть кейс, если у пользователя нет фамилии, и он вводит только имя ? 🙂
```js
human.fullName = 'Добби'
console.log(human.fullName)
```

2022-06-24 10:43 UTC, PonomareVlad commented on task_2/3.js
> +}
В задаче подразумевается передача функции трех аргументов: 
1. Массив слов
2. Минимальная длинна
3. Максимальная длинна

```js
_filter(["1", "22", "333", "4444"], 1, 3) // ["1", "22", "333"]
```

2022-06-24 14:35 UTC, Caveman21days commented on task_2/1.js
> +console.log(toArr('Hello mr reviewer'))
ну без регулярок или с ними, все равно придется перечислять все символы. Иного пути я не нашел, оставлю как есть

2022-06-24 14:58 UTC, Caveman21days commented on task_2/2.js
> +}
ну в этом случае, как и в любом другом с идентичными данными, я специально оставил как равные массивы. Вроде как не равные, но в том же руби вычтутся в ноль

2022-06-24 15:34 UTC, Caveman21days commented on task_2/6.js
> +}
честно говоря, понятнее не стало. Формулировку задания я так и не понял. Что значит "рандомная сотрировка". В первом случае будет 0011 или 1100, во втором шаффл массива. Наверное, с точки зрения формулировки более корректным выглядит первое решение. Хотя бы потому, что в задании есть слово "сортировка"

2022-06-24 15:40 UTC, PonomareVlad commented on task_2/6.js
> +}
Полагаю, что в задании подразумевается скорее перемешивание, чем какая-либо сортировка 🥲

2022-06-24 21:13 UTC, PonomareVlad requested changes
Нужно исправить ошибку в решении **8** задачи, и при желании, доработать решение задачи **2**

2022-06-24 21:13 UTC, PonomareVlad commented on task_2/8.js
>    }
Похоже, тут что-то пошло не так...
```js
human.dateOfBirth = new Date() // Sat Jun 25 2022 00:00:00 GMT+0000 (+00)
console.debug(human.dateOfBirth) // Invalid Date
```

2022-06-24 21:13 UTC, PonomareVlad commented on task_2/2.js
>  }
Попробуйте использовать тот же способ перебора, как вы делали для реверсии слова (через `for(...)`)

Также, обратите внимание на:
- [ ] `Array.length` — всегда возвращает полный размер массива с учетом _пустых_ индексов
- [ ] `Array.every()` (`forEach()`, `map()`, и т.д.) — не вызываются на _пустых_ индексах массива

2022-06-25 08:12 UTC, Caveman21days commented on task_2/8.js
>    }
я в упор не вижу ошибки в консоли

2022-06-25 08:12 UTC, Caveman21days commented on task_2/8.js
>    }
human.dateOfBirth = new Date()
Sat Jun 25 2022 13:11:34 GMT+0500 (Екатеринбург, стандартное время)
console.debug(human.dateOfBirth)
undefined
console.log(human.dateOfBirth)
VM305:1 Sat Jun 25 2022 00:00:00 GMT+0500 (Екатеринбург, стандартное время)
undefined

2022-06-25 08:14 UTC, Caveman21days commented on task_2/8.js
>    }
вы, может быть, старый вариант прогнали?

2022-06-25 10:46 UTC, PonomareVlad commented on task_2/8.js
>    }
Нет, похоже на баг в Safari — https://codepen.io/PonomareVlad/pen/ExQqMWJ

![Снимок экрана 2022-06-25 в 15 44 59](https://user-images.githubusercontent.com/2877584/175770235-12efc5ae-e097-4ba4-92dc-935eca0fde0d.png)

2022-06-25 10:54 UTC, PonomareVlad commented on task_2/8.js
> +      return new Date(`${this.monthOfBirth}.${this.dayOfBirth}.${this.yearOfBirth}`)
Попробуйте использовать [конструктор даты](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date) в таком формате:
```suggestion
      return new Date(this.yearOfBirth, this.monthOfBirth, this.dayOfBirth)
```

2022-06-27 15:38 UTC, merged