task_6 done
Caveman21days/js_tnk pull request #6
Opened 2022-07-15 10:40 UTC by Caveman21days

2022-07-15 13:25 UTC, PonomareVlad requested changes
Нужно проверить решение **первой** задачи

2022-07-15 13:25 UTC, PonomareVlad commented on task_6/1.js
> +    }
> В случае, если **в объекте** нет нужного **свойства** - **выбросить ошибку**,
если в объекте есть свойство, которое не используется в HTML - игнорировать .

Сейчас вы выбрасываете ошибку для всех **HTML элементов**, у которых нет **атрибута** `data-field` (даже для таких как [`<br>`](https://developer.mozilla.org/ru/docs/Web/HTML/Element/br), которые не могут содержать контент), а в случае отсутствия **свойства в объекте**, в HTML элемент выводится `undefined` без выброса ошибки

2022-07-15 13:25 UTC, PonomareVlad commented on task_6/2.js
> +const li = document.createElement("li");
Да, для отдельных модулей это идеальный вариант, а объявлять в функциях имеет смысл когда не хочется "загрязнять" текущую область видимости (например, в классе компонента)

2022-07-16 11:21 UTC, Caveman21days commented on task_6/1.js
> +    }
упс, совсем наоборот прочел задание

2022-07-16 16:32 UTC, PonomareVlad approved these changes
Отлично 👍🏻

2022-07-21 14:51 UTC, merged